services:
  - type: web
    name: familles-rurales
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails assets:clean
    startCommand: bundle exec rails db:migrate && bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_SERVE_STATIC_FILES
        value: "1"
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: familles-rurales-db
          property: connectionString

databases:
  - name: familles-rurales-db
    plan: free
