default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: familles_rurales_development

test:
  <<: *default
  database: familles_rurales_test

production:
  primary: &production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *production
    migrations_paths: db/cache_migrate
  queue:
    <<: *production
    migrations_paths: db/queue_migrate
  cable:
    <<: *production
    migrations_paths: db/cable_migrate
